// Tablas de datos del generador: carátulas, alias y sufijos de ruta.
// Extraído de index.js para reducir tokens al editar. No tocar a mano la lógica.
// Este archivo NO ejecuta nada: solo exporta datos.

const TITLE_ALIASES = {
  // Ghibli & anime pelis
  'El viaje de Chihiro': 'Spirited Away',
  'Mi vecino Totoro': 'My Neighbor Totoro',
  'La princesa Mononoke': 'Princess Mononoke',
  'La Tumba de las Luciérnagas': 'Grave of the Fireflies',
  'El Castillo en el aire - La leyenda de Laputa': 'Castle in the Sky',
  'El Infierno de Dante': 'Dante\'s Inferno',
  'La chica que saltaba através del tiempo': 'The Girl Who Leapt Through Time',
  'Puedo escuchar el mar': 'I Can Hear the Sea',
  'Viaje a Agartha': 'Journey to Agartha',
  'Hadashi no Gen 1&2 (Barefoot Gen)': 'Barefoot Gen',
  'Vampire Hunter + Bloodlust': 'Vampire Hunter D Bloodlust',
  'Cuentos de Terramar': 'Tales from Earthsea',
  'Ovelord Ovas + special': 'Overlord',
  'Astérix y Obélix La batalla de los jefes': 'Asterix: The Big Fight',
  'Aggresive Retsuko': 'Aggretsuko',
  'La leyenda de Korra': 'The Legend of Korra',
  'Sand Lands': 'Sand Land',
  'Mononoke Karakasa & Shou - Hinezumi': 'Mononoke',
  'Mononoke Movie Dai-2 Shou - Hinezumi': 'Mononoke',
  'El Castillo en el cielo - Tenku no Shiro Laputa': 'Castle in the Sky',
  'Layton Kyouju to Eien no Utahime': 'Professor Layton and the Eternal Diva',
  'Death Note Rewrite': 'Death Note',
  'Tenrou Sirius the Jaeger': 'Sirius the Jaeger',
  'Forky Ask a Question': 'Forky Asks a Question',
  'Ren y Stimpy': 'The Ren & Stimpy Show',
  'Patoaventuras': 'DuckTales',
  'El Laboratorio de Dexter': 'Dexter\'s Laboratory',
  'Los Simpsons': 'The Simpsons',
  'Codigo KND': 'Codename: Kids Next Door',
  'Capitan N el amo del videojuego': 'Captain N',
  'Capitán Cavernícola': 'Captain Caveman',
  'Pepe Potamo': 'The Peter Potamus Show',
  'Chopy y la princesa': 'Choppy and the Princess',
  'Las Maravillosas Desventuras de Flapjack': 'The Marvelous Misadventures of Flapjack',
  'El rey de la colina': 'King of the Hill',
  'Ed, Edd y Eddy': 'Ed, Edd n Eddy',
  'Ed Edd y Eddy': 'Ed, Edd n Eddy',
  'Las Macabras aventuras de Billy y Mandy': 'The Grim Adventures of Billy & Mandy',
  'Las Supernenas': 'The Powerpuff Girls',
  'El Castillo en el cielo - Tenkū no Shiro Laputa': 'Laputa: Castle in the Sky',
  'Maguila Gorila': 'Magilla Gorilla',
  'La Aldea del arce': 'Maison Ikkoku',
  'La Tropa Goofy': 'Goof Troop',
  'La Leyenda de Zelda': 'The Legend of Zelda',
  'Las Aventuras de Tintin': 'The Adventures of Tintin',
  'Soy Comadreja': 'I Am Weasel',
  'Oggy y las cucarachas': 'Oggy and the Cockroaches',
  'Brandy y Mr Whiskers': 'Brandy & Mr. Whiskers',
  'Osos Revoltosos': 'We Bare Bears',
  'Rocky y Bullwinkle': 'The Adventures of Rocky and Bullwinkle',
  'La Pajareria de Transilvania': 'Count Duckula',
  'Figaro y Cleo': 'Figaro and Cleo',
  'Los Oblongs': 'The Oblongs',
  'Beavis and Butt-Head Remastered': 'Beavis and Butt-Head',
  'La conserje Pokémon': 'Pokémon',
  'Crónicas Pokémon': 'Pokémon',
  'Pokémon Megaevolución': 'Pokémon',
  'Pokémon Origin': 'Pokémon',
  'BeyBlade 2000': 'Beyblade',
  'BeyBlade Burst Evolution': 'Beyblade Burst',
  'BeyBlade Burst Turbo': 'Beyblade Burst',
  'Choppy y la princesa': 'Choppy and the Princess',
  'Final Fantasy V': 'Final Fantasy',
  'La brigada de los sepultureros': 'The Munsters',
  'La M palabra y Tontico': 'The Smurfs',
  'Los Terribles Gemelos Cramp': 'The Cramp Twins',
  'Jackie y Nuca': 'Jackie and Nuca',
  'Belfy Y Lillibit': 'Belfy and Lillibit',
  'Virkikis': 'Virkikis',
  'Serie Kinki': 'Serie Kinki',
  'Rertorno a Lilifor': 'Return to Lillifor',
  'Naranjito, fútbol en acción': 'Naranjito',
  'Cocodrilos al rescate': 'Rescue Crocodiles',
  'En busca de Carmen Sandiego': 'Where on Earth Is Carmen Sandiego?',
  'La Tortuga DArtagnan y Dum Dum': 'Dogtanian',
  'Teenage Mutant Ninja Tuuurtles': 'Teenage Mutant Ninja Turtles',
  'HeroesinahalfshellNANANA': 'Teenage Mutant Ninja Turtles',
  'Banner y Flappy': 'Banner and Flappy',
  'Abbot y Costello': 'Abbott and Costello',
  'Los Fruitis': 'The Fruitties',
  'Pesadillas (Goosebumps) de R L Stine': 'Goosebumps',
  'La zapatero y la Princesa': 'The Thief and the Cobbler',
  'El Zapatero y la Princesa (El Ladrón de Bagdad)': 'The Thief and the Cobbler',
  'El cuentacuentos': 'The Storyteller',
  'El conde Pátula': 'Count Duckula',
  'Rafaela Y Su Loco Mundo': 'Rafaela',
  'Quentin Taran tantarantino': 'Quentin Tarantino',
  'QVMT': 'Qué vida más triste',
  'QVMT TEMPORADA 0': 'Qué vida más triste',
  'QVMT TEMPORADA 1': 'Qué vida más triste',
  'QVMT TEMPORADA 2': 'Qué vida más triste',
  'QVMT TEMPORADA 3': 'Qué vida más triste',
  'QVMT TEMPORADA 4': 'Qué vida más triste',
  'QVMT TEMPORADA 5': 'Qué vida más triste',
  'QVMT TEMPORADA 6': 'Qué vida más triste',
  'QVMT TEMPORADA 7': 'Qué vida más triste',
  'Off the air': 'Off the Air',
  'Peep show': 'Peep Show',
  'Robot chicken': 'Robot Chicken',
  'Trailer Park Boys': 'Trailer Park Boys',
  'Problem Solverz': 'The Problem Solverz',
  'Superjail': 'Superjail!',
  'Triptank': 'Triptank',
  'Archer': 'Archer',
  'Monty Python Flying Circus': 'Monty Python\'s Flying Circus',

  // === FIXES y nuevos aliases ===
  'De yakuza a amo de casa': 'The Way of the Househusband',
  'El inspector Gadget': 'Inspector Gadget (1983)',
  'La Familia Addams': 'The Addams Family (1992)',
  'Flint y los viajeros del tiempo': 'Flint the Time Detective',
  'Chicho Terremoto': 'Chicho Terremoto',
  'Historias de fútbol': 'Historias de fútbol',
  'Super Mario Wolrd': 'Super Mario World',
  'Super Mario World': 'Super Mario World',
  'Bumpy el travieso': 'Bumpy',
  'Campeones hacia el mundial': 'Captain Tsubasa',
  'Campeones': 'Captain Tsubasa',
  'DBZKai': 'Dragon Ball Z Kai',
  'Jeff y unos aliens': 'Jeff & Some Aliens',
  'Mr Pickles': 'Mr. Pickles',
  'Rick y Morty': 'Rick and Morty',
  'Beetlejuice la serie de dibujos': 'Beetlejuice: The Animated Series',
  'Daniel el travieso': 'Dennis the Menace',
  'La banda del patio': 'Recess',
  'Las aventuras de Super Mario Bros 3': 'Super Mario Bros. 3',
  'Los Snorkels': 'Snorks',
  'Mozart': 'Viva la banda de Mozart',
  'Sonic': 'Adventures of Sonic the Hedgehog',
  // === Alias con clave normalizada (sin paréntesis) ===
  'Agallas el perro cobarde': 'Courage the Cowardly Dog',
  'Vaca y Pollo': 'Cow and Chicken',
  'Itou Junji Collection': 'Junji Ito Collection',
  'Itou Junji Maniac': 'Junji Ito Maniac',
  'Itou Junji Tomie': 'Tomie',
  'Canuto y Canito': 'Heckle and Jeckle',
  'Abbott y Costello': 'Abbott and Costello',
  'El libro de la selva': 'The Jungle Book',
  'Pesadillas de R L Stine': 'Goosebumps',
  'Hadashi no Gen 1&2': 'Barefoot Gen',
  'El Zapatero y la Princesa': 'The Thief and the Cobbler',
  'Relatos de los hermanos Grimm': 'The Wonderful World of the Brothers Grimm',
};

const CUSTOM_POSTERS = {
  'Navajeros': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/navajeros.jpg',
  'Una carta para Momo': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/una_carta_para_momo_v2.jpg',
  'Los niños lobo Ame y Yuki': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/los_ninos_lobo_v2.jpg',
  'Los niños lobo': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/los_ninos_lobo_v2.jpg',
  'Basket Fever': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/basket_fever.jpg',
  'Campeones': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/campeones.jpg',
  'Daniel el travieso': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/daniel_el_travieso.jpg',
  'Daniel el Travieso': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/daniel_el_travieso.jpg',
  'La banda del patio': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/la_banda_del_patio.jpg',
  'Los Fruitis': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/los_fruitis.jpg',
  'Los Trotamusicos': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/los_trotamusicos.jpg',
  'Mortadelo y Filemón': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/mortadelo_y_filem_n.jpg',
  'Nicolás': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/nicol_s.jpg',
  'Sylvan': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/sylvan.jpg',
  'Isidoro': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/isidoro.jpg',
  'Rick y Morty': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/rick_y_morty.jpg',
  'Pokemon': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/pokemon.jpg',
  'Pokémon': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/pokemon.jpg',
  'Los Snorkels': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/los_snorkels.jpg',
  'Chicho Terremoto': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/chicho_terremoto.jpg',
  'Cocodrilos al rescate': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/cocodrilos_al_rescate.jpg',
  'Cosas de locos': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/cosas_de_locos.jpg',
  'Cosas de locos!': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/cosas_de_locos.jpg',
  'Cosas de Locos!': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/cosas_de_locos.jpg',
  'Las aventuras de Super Mario Bros 3': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/las_aventuras_de_super_mario_bros_3.jpg',
  'Los intocables de Elliot Mouse': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/los_intocables_de_elliot_mouse.jpg',
  'Super Mario World': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/super_mario_world.jpg',
  'Beetlejuice la serie de dibujos': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/beetlejuice_la_serie_de_dibujos.jpg',
  'Beetlejuice': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/beetlejuice_la_serie_de_dibujos.jpg',
  'Regreso al Futuro': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/regreso_al_futuro.jpg',
  'Regreso al futuro': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/regreso_al_futuro.jpg',
  'Bumpy': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/bumpy.jpg',
  'Bumpy el travieso': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/bumpy.jpg',
  'El inspector Gadget': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/el_inspector_gadget.jpg',
  'Historias de fútbol': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/historias_de_f_tbol.jpg',
  'La familia addams': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/la_familia_addams.jpg',
  'La Familia Addams': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/la_familia_addams.jpg',
  'La pajareria de transilvania': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/la_pajareria_de_transilvania.jpg',
  'La Pajareria de Transilvania': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/la_pajareria_de_transilvania.jpg',
  'Mozart': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/mozart.jpg',
  'Sonic': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/sonic.jpg',
  'Teenage Mutant Ninja Tuuurtles': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/teenage_mutant_ninja_turtles.jpg',
  'Teenage Mutant Ninja Turtles': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/teenage_mutant_ninja_turtles.jpg',
  'Dragon ball trilogia + eplis': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/dragon_ball_trilogia___eplis.jpg',
  'Astérix y Obélix La batalla de los jefes': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/asterix_y_obelix_la_batalla_de_los_jefes.jpg',
  'De yakuza a amo de casa': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/de_yakuza_a_amo_de_casa.jpg',
  'Mr': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/mr.jpg',
  'Puedo escuchar el mar': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/puedo_escuchar_el_mar.jpg',
  'Viaje a Agartha': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/viaje_a_agartha.jpg',
  'El Castillo en el cielo - Tenku no Shiro Laputa': 'https://www.jbhifi.com.au/cdn/shop/products/134794-Product-0-I_ac1f5019-39f5-41c4-9fd7-8590c3ac70db.jpg?v=1572269844',
  'Pet Shop of Horror': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/pet_shop_of_horror.jpg',
  'Beavis & Butt-Head': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4GaNJRLkGk6O_n-zP09b5k6hfvVoKmgWPcpCQPZ4zL_RCyA4RskSQ87PR&s=10',
  'Beavis & Butt-Head/eplis': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/beavis2.png',
  'Beavis & Butt-Head T0': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/beavis_butt_head_t0.jpg',
  'Beavis & Butt-Head T1': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/beavis_butt_head_t1.jpg',
  'Beavis & Butt-Head T2': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/beavis_butt_head_t2.jpg',
  'Beavis & Butt-Head T3': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/beavis_butt_head_t3.jpg',
  'Beavis & Butt-Head T4': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/beavis_butt_head_t4.jpg',
  'Beavis & Butt-Head T5': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/beavis_butt_head_t5.jpg',
  'Beavis & Butt-Head T6': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/beavis_butt_head_t6.jpg',
  'Beavis & Butt-Head T7': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/beavis_butt_head_t7.jpg',
  'Beavis & Butt-Head T8': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/beavis_butt_head_t8.jpg',
  'Beavis & Butt-Head T9': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/beavis_butt_head_t9.jpg',
  'Beavis & Butt-Head T10': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/beavis_butt_head_t10.jpg',
  'Beavis & Butt-Head T11': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/beavis_butt_head_t11.jpg',
  'Dinosaurios': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/dinosaurios.jpg',
  'Pesadillas (Goosebumps) de R L Stine': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/pesadillas_goosebumps.jpg',
  'El Inquilino': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/el_inquilino.jpg',
  'Que Bello Es Sobrevivir': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/que_bello_es_sobrevivir.jpg',
  'Quien da la vez': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/quien_da_la_vez.jpg',
  'Enjuto Mojamuto': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/enjuto_mojamuto.jpg',
  'La M palabra y Tontico': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/la_m_palabra_y_tontico.jpg',
  'Rertorno a Lilifor': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/rertorno_a_lilifor.jpg',
  'Retorno a Lilifor': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/rertorno_a_lilifor.jpg',
  'Museo Coconut': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/museo_coconut.jpg',
  'Rafaela Y Su Loco Mundo': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/rafaela_y_su_loco_mundo.jpg',
  'Abbott y Costello': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/abbott_y_costello.jpg',
  'Alicia en el pais de las maravillas': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/alicia_en_el_pais_de_las_maravillas.jpg',
  'Belfy Y Lillibit': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/belfy_y_lillibit.jpg',
  'Canuto y Canito': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/canito_y_canuto.jpg',
  'Canito y Canuto': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/canito_y_canuto.jpg',
  'Celia': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/celia.jpg',
  'Chopy y la princesa': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/chopy_y_la_princesa.jpg',
  'Don Drácula': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/don_dracula.jpg',
  'El conde Pátula': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/el_conde_patula.jpg',
  'El cuentacuentos': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/el_cuentacuentos.jpg',
  'El libro de la selva': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/el_libro_de_la_selva.jpg',
  'Final Fantasy V': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/final_fantasy_v.jpg',
  'Jackie y Nuca': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/jackie_y_nuca.jpg',
  'La Aldea del arce': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/la_aldea_del_arce.jpg',
  'Las Aventuras de Tintin': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/tintin.jpg',
  'Los osos montañeses': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/los_osos_montaneses.jpg',
  'Mofli': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/mofli.jpg',
  'Naranjito, fútbol en acción': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/naranjito_futbol_en_accion.jpg',
  'Osos Revoltosos': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/osos_revoltosos.jpg',
  'Relatos de los hermanos Grimm': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/relatos_de_los_hermanos_grimm.jpg',
  'Simbad': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/simbad.jpg',
  'Sinbad': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/simbad.jpg',
  'Virkikis': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/los_monchicchis.jpg',
  'Virtua Fighter': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/virtua_fighter.jpg',
  'WillyFog': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/willyfog.jpg',
  'Una Navidad con Mickey': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/una_navidad_con_mickey.jpg',
  'Pepe Potamo': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/pepe_potamo.jpg',
  'Digimon Adventure': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/digimon_adventure.jpg',
  'Digimon Adventure 02': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/digimon_adventure_02.jpg',
  'Digimon tamers': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/digimon_tamers.jpg',
  'Digimon Frontier': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/digimon_frontier.jpg',
  'Digimon Data Squad': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/digimon_data_squad.jpg',
  'Digimon Adventure Remake (2020)': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/digimon_adventure_remake.jpg',
  'Digimon Adventure (2020)': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/digimon_adventure_remake.jpg',
  'T1 - Digimon Adventure': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/digimon_adventure.jpg',
  'T2 - Digimon Adventure 02': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/digimon_adventure_02.jpg',
  'T3 - Digimon Tamers': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/digimon_tamers.jpg',
  'T4 - Digimon Frontier': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/digimon_frontier.jpg',
  'T5 - Digimon Savers': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/digimon_data_squad.jpg',
  'Spider-Man': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/spiderman_serie_animada.jpg',
  'Los ladrones van a la oficina': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/los_ladrones_van_a_la_oficina.jpg',
};

const PATH_POSTER_SUFFIXES = {
  'Rick y Morty/\u00aanime': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/rick_y_morty_anime.jpg',
  'Festivales del tiri/Primer festival': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/festival_primero.jpg',
  'Festivales del tiri/Segundo festival': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/festival_segundo.jpg',
  'Festivales del tiri/Tercer festival': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/festival_tercero.jpg',
  'Festivales del tiri': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/festivales_por_capis.jpg',
  'Festivales por capis': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/festivales_por_capis.jpg',
  'Dragon Ball/Pelis': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/db_pelis.jpg',
  'Dragon Ball Super/Pelis': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/dbs_pelis.jpg',
  'Dragon Ball Z - Selecta Vision/Pelis+especiales': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/dbz_pelis_especiales.jpg',
  'Dragon Ball Z - Selecta Vision/1. Saga Saiyan (1-35)': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/dbz_saga_saiyan.jpg',
  'Dragon Ball Z - Selecta Vision/2.Saga Freezer (36-107)': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/dbz_saga_freezer.jpg',
  'Dragon Ball Z - Selecta Vision/3.Saga Garlick Jr. (108-117)': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/dbz_saga_garlick.jpg',
  'Dragon Ball Z - Selecta Vision/4.Saga Androides y Cell (118-194)': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/dbz_saga_androides.jpg',
  'Dragon Ball Z - Selecta Vision/5.Saga del Otro Mundo (195-199)': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/dbz_saga_otro_mundo.jpg',
  'Dragon Ball Z - Selecta Vision/6.Saga Buu (200-291)': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/dbz_saga_buu.jpg',
  'Pokémon/1. Kanto': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/pokemon_kanto.jpg',
  'Pokémon/2. Johto': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/pokemon_johto.jpg',
  'Pokémon/3. Hoenn': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/pokemon_hoenn.jpg',
  'Pokémon/4. Sinnoh': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/pokemon_sinnoh.jpg',
  'Pokémon/5. Teselia': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/pokemon_teselia.jpg',
  'Pokémon/6. Kalos': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/pokemon_kalos.jpg',
  'Pokémon/7. Alola': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/pokemon_alola.jpg',
  'Pokémon/8. Galar (Viajes Pokémon)': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/pokemon_galar.jpg',
  'Pokémon/9. Paldea (Pokémon Horizontes)': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/pokemon_paldea.jpg',
  'Pokémon/Crónicas Pokémon': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/pokemon_cronicas.jpg',
  'Pokémon/La conserje Pokémon': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/pokemon_conserje.jpg',
  'Pokémon/Pokémon Megaevolución': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/pokemon_megaevolucion.jpg',
  'Pokémon/Pokémon Origin': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/pokemon_origin.jpg',
  'Tres amigos y Jerry': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/jerry.png',
  'Hora de Aventuras/T1': 'https://image.tmdb.org/t/p/w500/vpnV0g2VOounP0kHNi86oBPceMY.jpg',
  'Hora de Aventuras/T2': 'https://image.tmdb.org/t/p/w500/vpnV0g2VOounP0kHNi86oBPceMY.jpg',
  'Hora de Aventuras/T3': 'https://image.tmdb.org/t/p/w500/vpnV0g2VOounP0kHNi86oBPceMY.jpg',
  'Hora de Aventuras/T4': 'https://image.tmdb.org/t/p/w500/vpnV0g2VOounP0kHNi86oBPceMY.jpg',
  'Hora de Aventuras/T5': 'https://image.tmdb.org/t/p/w500/vpnV0g2VOounP0kHNi86oBPceMY.jpg',
  'Hora de Aventuras/T6': 'https://image.tmdb.org/t/p/w500/vpnV0g2VOounP0kHNi86oBPceMY.jpg',
  'Hora de Aventuras/T7': 'https://image.tmdb.org/t/p/w500/vpnV0g2VOounP0kHNi86oBPceMY.jpg',
  'Hora de Aventuras/T8': 'https://image.tmdb.org/t/p/w500/vpnV0g2VOounP0kHNi86oBPceMY.jpg',
  'Hora de Aventuras/T9': 'https://image.tmdb.org/t/p/w500/vpnV0g2VOounP0kHNi86oBPceMY.jpg',
  'Hora de Aventuras/T10': 'https://image.tmdb.org/t/p/w500/vpnV0g2VOounP0kHNi86oBPceMY.jpg',
  'Los Terribles Gemelos Cramp': 'https://image.tmdb.org/t/p/w500/vDbVBSQJx4xz7FAaOoJG9IFhAsB.jpg',
  'Akira Kurosawa': 'https://m.media-amazon.com/images/I/91fPGYM7PyL._AC_UF894,1000_QL80_.jpg',
  "Monty's movies": 'https://m.media-amazon.com/images/I/710PzQnaomL._AC_UF894,1000_QL80_.jpg',
  'Sergei Eisentein': 'https://upload.wikimedia.org/wikipedia/commons/2/26/Sergei_Eisenstein_03.jpg',
  'Sine Kinki': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/sine_kinki.jpg',
  'Stephen King': 'https://i.pinimg.com/736x/5d/43/bd/5d43bdd12310bc686a71e4fedbf20590.jpg',
  'Disney/Cortos': 'https://cdn.artphotolimited.com/images/61a73c0dbd40b81766e77efb/1000x1000/walt-disney.jpg',
  'Disney/Pelis': 'https://cdn.artphotolimited.com/images/61a73c0dbd40b81766e77efb/1000x1000/walt-disney.jpg',
  'Disney/Cortos/Relatos de Disney': 'https://cdn.artphotolimited.com/images/61a73c0dbd40b81766e77efb/1000x1000/walt-disney.jpg',
  'Bumpy y sus amigos': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqoKEI0enZnyr-NoTQbkGqd6EMNbqmUEs2WbmEpkJKUQ&s=10',
  'Street Fighter II': 'https://image.tmdb.org/t/p/w500/p7VSebvaZ6eWTrJDFh1sV7h6GV2.jpg',
  'Asterix/Asterix dibus': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzo79gkoUV9SyK7C_DP07m2ReCyifEvQOSct-1hOu8i9jre1YorLnLo8q1&s=10',
  'Asterix/Asterix no dibus': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/asterix_no_dibus.png',
  'Un Millán de cosas': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/un_millan_de_cosas.png',
  'BeyBlade/BeyBlade 2000': 'https://i.pinimg.com/736x/cf/4d/84/cf4d8495233cddf795f5dea41a6dd398.jpg',
  'BeyBlade/BeyBlade Burst': 'https://i.pinimg.com/736x/cf/4d/84/cf4d8495233cddf795f5dea41a6dd398.jpg',
  'BeyBlade/BeyBlade Burst Evolution': 'https://cdn2.steamgriddb.com/grid/87d7515a647f2f8ff7d92f38820dd8c7.png',
  'BeyBlade/BeyBlade Burst Turbo': 'https://i.pinimg.com/736x/83/a3/fb/83a3fbb921271d1ca5a07f2e1903e1bc.jpg',
  // Temporadas de BeyBlade renumeradas (1. .. 3., las demás se borraron de Terabox)
  'BeyBlade/1.BeyBlade 2000': 'https://i.pinimg.com/736x/cf/4d/84/cf4d8495233cddf795f5dea41a6dd398.jpg',
  'BeyBlade/2.BeyBalde V-Force': 'https://cdn2.steamgriddb.com/grid/87d7515a647f2f8ff7d92f38820dd8c7.png',
  'BeyBlade/3.BeyBlade G-Revolution': 'https://i.pinimg.com/736x/83/a3/fb/83a3fbb921271d1ca5a07f2e1903e1bc.jpg',
  'La brigada de los sepultureros': 'https://static.filmin.es/images/es/media/38022/1/poster_0_3.jpg',
  'La leyenda de Korra': 'https://image.tmdb.org/t/p/original/eMo4uWsN3qceNhBPcuw5T2lFsc5.jpg',
  'Vaca y Pollo': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/vaca_y_pollo.jpg',
  'Soy Comadreja': 'https://image.tmdb.org/t/p/original/j71oaLzJoU7CXP6v5GEfZZ9VQtX.jpg',
  'THE ELECTRIC WIZARD BY EOIN O`KANE': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/electric_wizard.png',
  'Avatar La Leyenda de Aang/T1': 'https://m.media-amazon.com/images/M/MV5BZTZmMWU3ZTUtM2U4Ni00YmNhLTkwODktN2IzNzkyZmRlYjZjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
  'Avatar La Leyenda de Aang/T2': 'https://m.media-amazon.com/images/M/MV5BZTZmMWU3ZTUtM2U4Ni00YmNhLTkwODktN2IzNzkyZmRlYjZjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
  'Avatar La Leyenda de Aang/T3': 'https://m.media-amazon.com/images/M/MV5BZTZmMWU3ZTUtM2U4Ni00YmNhLTkwODktN2IzNzkyZmRlYjZjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
  'Asterix': 'https://postersonline.co.za/wp-content/uploads/2026/05/GPE5727.jpg',
  'Devil May Cry': 'https://m.media-amazon.com/images/M/MV5BMWZiMTVmMjEtYjQ4MS00YzE4LThmMGYtYTE3ZjhhZmQ2NmMwXkEyXkFqcGc@._V1_.jpg',
  'High Score Girl/s1': 'https://takamakiokerar.wordpress.com/wp-content/uploads/2018/12/tumblr_mfeera8z4r1qbfiiuo1_1280.jpg',
  'High Score Girl/s2': 'https://takamakiokerar.wordpress.com/wp-content/uploads/2018/12/tumblr_mfeera8z4r1qbfiiuo1_1280.jpg',
  'Mononoke Karakasa & Shou - Hinezumi (Netflix)': 'https://static.wikia.nocookie.net/wiki-doblaje-espana/images/3/3d/Mononoke_-_El_Fantasma_Bajo_La_Lluvia_-_Poster.jpg/revision/latest?cb=20241116234056&path-prefix=es',
  'Tenshi no Tamago': 'https://m.media-amazon.com/images/M/MV5BYmU1ZDEyNzEtMWYyZi00OTc2LTgxMmEtZWU3YzMxNTUwM2YzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
  'Urotsukidoji - La leyenda del se\u00f1or del mal': 'https://m.media-amazon.com/images/I/61SNyC4jnmL._AC_UF894,1000_QL80_.jpg',
  'La banda del patio/Especiales': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/la_banda_del_patio.jpg',
  'La banda del patio/T1': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/la_banda_del_patio.jpg',
  'La banda del patio/T2': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/la_banda_del_patio.jpg',
  'La banda del patio/T3': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/la_banda_del_patio.jpg',
  'La banda del patio/T4': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/la_banda_del_patio.jpg',
  'La banda del patio/T5': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/la_banda_del_patio.jpg',
  'La banda del patio/T6': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/la_banda_del_patio.jpg',
  'El Zapatero y la Princesa (El Ladrón de Bagdad)': 'https://image.tmdb.org/t/p/w500/3OKtFuTxahr7hokPB9aO38qgOfc.jpg',
  'The Thief and the Cobbler Recobbled Cut Mark 4 WIP 19⁄09⁄13': 'https://image.tmdb.org/t/p/w500/3OKtFuTxahr7hokPB9aO38qgOfc.jpg',
  'The Thief and the Cobbler Recobbled Cut Mark 5 WIP 06⁄20⁄23': 'https://image.tmdb.org/t/p/w500/3OKtFuTxahr7hokPB9aO38qgOfc.jpg',
  'Gyakuten Saiban - Ace Attorney': 'https://m.media-amazon.com/images/I/71rWSoCx8fL._AC_UF894,1000_QL80_.jpg',
  'Gyakuten Saiban - Ace Attorney/s1': 'https://m.media-amazon.com/images/I/71rWSoCx8fL._AC_UF894,1000_QL80_.jpg',
  'Gyakuten Saiban - Ace Attorney/s2': 'https://m.media-amazon.com/images/I/71rWSoCx8fL._AC_UF894,1000_QL80_.jpg',
  'Monster': 'https://m.media-amazon.com/images/M/MV5BYzU2MWQ5NGQtYmNlMC00ZjJkLWJmODItZDM5MDM3YmUyMWJkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
  'Overlord/s1': 'https://m.media-amazon.com/images/M/MV5BYjNjNDBmZjAtMGZiMS00ODBkLWFjYWItZWQ1ZjEwOGNmZDBjXkEyXkFqcGc@._V1_.jpg',
  'Overlord/s2': 'https://m.media-amazon.com/images/M/MV5BYjNjNDBmZjAtMGZiMS00ODBkLWFjYWItZWQ1ZjEwOGNmZDBjXkEyXkFqcGc@._V1_.jpg',
  'Overlord/s3': 'https://m.media-amazon.com/images/M/MV5BYjNjNDBmZjAtMGZiMS00ODBkLWFjYWItZWQ1ZjEwOGNmZDBjXkEyXkFqcGc@._V1_.jpg',
  'Overlord/s4': 'https://m.media-amazon.com/images/M/MV5BYjNjNDBmZjAtMGZiMS00ODBkLWFjYWItZWQ1ZjEwOGNmZDBjXkEyXkFqcGc@._V1_.jpg',
  'Overlord/Ovas + special/Ovelord Ovas + special': 'https://m.media-amazon.com/images/M/MV5BYjNjNDBmZjAtMGZiMS00ODBkLWFjYWItZWQ1ZjEwOGNmZDBjXkEyXkFqcGc@._V1_.jpg',
  'Steins;Gate Movie Fuka Ryouiki no Déjà vu': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/sgmovie.jpg',
  'Juego de Tronos': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/juego_de_tronos.jpg',
  'La casa del dragón': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/la_casa_del_dragon.jpg',
  'El Castillo en el cielo - Tenkū no Shiro Laputa': 'https://www.jbhifi.com.au/cdn/shop/products/134794-Product-0-I_ac1f5019-39f5-41c4-9fd7-8590c3ac70db.jpg?v=1572269844',
};

const FILE_TITLE_ALIASES = {
  'El jovencito Frankenstein': "Young Frankenstein",
  'La vida de Brian BDrip': "Monty Python's Life of Brian",
  'Los caballeros de la mesa cuadrada': 'Monty Python and the Holy Grail',
  'El sentido de la vida': "Monty Python's The Meaning of Life",
  'El gigante de hierro': 'The Iron Giant',
  'La sustancia': 'The Substance',
  'Idiocracia': 'Idiocracy',
  'Rebelión en la granja': 'Animal Farm',
  'El Planeta Salvaje': 'Fantastic Planet',
  'Gigante': 'Giant',
  'Super Mario Bros La': 'The Super Mario Bros Movie',
  'Taron y el caldero magico': 'The Black Cauldron',
  'Tim Burton James Y El Melocoton Gigante': 'James and the Giant Peach',
  'Una Navidad con Mickey': "Mickey's Christmas Carol",
  'Duelo silencioso': 'The Quiet Duel',
  'El Angel Borracho': 'Drunken Angel',
  'La fortaleza escondida': 'The Hidden Fortress',
  'Los canallas duermen en paz': 'The Bad Sleep Well',
  'Trono de sangre': 'Throne of Blood',
  'Los sueños de Akira Kurosawa': "Akira Kurosawa's Dreams",
  'Tygra Hielo y Fuego': 'Fire and Ice',
  'Los surfistas nazis deben morir': 'Surf Nazis Must Die',
  'La mesita del comedor': 'The Coffee Table',
  'Premutos El Angel Caido': 'Premutos',
  'Operación Ogro': 'Ogro',
  'El Condon Asesino': 'Killer Condom',
  'Cheap aka Down and Dirty Duck': 'Down and Dirty Duck',
  'Asterix El Galo': 'Asterix the Gaul',
  'Asterix Y Cleopatra': 'Asterix and Cleopatra',
  'Las doce pruebas de Asterix': 'The Twelve Tasks of Asterix',
  'Astérix Y la sorpresa del César': 'Asterix vs Caesar',
  'Asterix En Bretaña': 'Asterix in Britain',
  'Asterix Y el golpe del menhir': 'Asterix and the Big Fight',
  'Asterix En America': 'Asterix Conquers America',
  'Astérix Y los vikingos': 'Asterix and the Vikings',
  'Astérix En los juegos olimpicos': 'Asterix at the Olympic Games',
  'Asterix La residencia de los dioses': 'Asterix The Mansions of the Gods',
  'Astérix El secreto de la poción mágica': 'Asterix The Secret of the Magic Potion',
  'Astérix y Obélix y El ReinoMedio': 'Asterix and Obelix The Middle Kingdom',
  'El Acorazado Potemkin': 'Battleship Potemkin',
  'La Linea General': 'The General Line',
  'Ivan El Terrible I': 'Ivan the Terrible Part I',
  'Ivan El Terrible II': 'Ivan the Terrible Part II',
  '¿Qué he hecho yo para merecer esto': 'What Have I Done to Deserve This',
  'Pinocho la leyenda': 'The Adventures of Pinocchio',
};

const FILE_POSTER_URLS = {
  'Primer Festival de Mortadelo y Filemón Estudios Vara 1969': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/festival_primero.jpg',
  'Segundo Festival de Mortadelo y Filemón Estudios Vara 1970': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/festival_segundo.jpg',
  'Tercer Festival de Mortadelo y Filemón Estudios Vara 1971': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/festival_tercero.jpg',
  'Pokémon - P01 - Mewtwo Vs Mew': 'https://m.media-amazon.com/images/M/MV5BNDg0ZDk2N2QtZDQzYi00ZTljLWExODgtZWQ2Y2YzZTA1NjVjXkEyXkFqcGc@._V1_SX300.jpg',
  'Pokémon - P01.1 - Mewtwo El regreso': 'https://m.media-amazon.com/images/M/MV5BMTM4NTAxMTQ4OV5BMl5BanBnXkFtZTYwNTM2MjI5._V1_SX300.jpg',
  'Pokémon - P02 - El poder de uno': 'https://m.media-amazon.com/images/M/MV5BOTE0NzY5MGUtZDdjMi00OTMyLThiYmEtOTc5NWY0NTE3NDA0XkEyXkFqcGc@._V1_SX300.jpg',
  'Pokémon - P03 - El Hechizo de los Unown': 'https://m.media-amazon.com/images/M/MV5BMTk0NzM3MDY1OV5BMl5BanBnXkFtZTYwNTkwODc5._V1_SX300.jpg',
  'Pokémon - P04 - Celebi, la Voz del Bosque': 'https://m.media-amazon.com/images/M/MV5BZjgyMzI2ODgtNGEyNC00N2U0LTgzMDQtMzgwMDI5YWFlYTliXkEyXkFqcGc@._V1_SX300.jpg',
  'Pokémon - P05 - Héroes, Latios y Latias': 'https://m.media-amazon.com/images/M/MV5BYWJlMGQxNDYtZTc5NC00MzlhLWI1MTItZmU1NjY1MTRlZjFjXkEyXkFqcGc@._V1_SX300.jpg',
  'Pokémon - P06 - Jirachi y los Deseos SUB': 'https://m.media-amazon.com/images/M/MV5BNjVmYTZkZjUtMGVhNS00NjQwLWIyM2UtYWNkZjNiYTY1ZjhhXkEyXkFqcGc@._V1_SX300.jpg',
  'Pokémon - P07 - El Destino de Deoxys SUB': 'https://image.tmdb.org/t/p/w500/3UV4evNh70gvPZB9KJEoh3a9B6I.jpg',
  'Pokémon - P08 - Lucario y el Misterio de Mew': 'https://m.media-amazon.com/images/M/MV5BODg1NzkzODMtMmNjYi00YWNmLWI3OGUtZjc0YzVjMjU5YzJmXkEyXkFqcGc@._V1_SX300.jpg',
  'Pokémon - P09 - Ranger y el Templo del Mar': 'https://m.media-amazon.com/images/M/MV5BMTczNjg3MDgyOV5BMl5BanBnXkFtZTgwMTc2MzQ2NjE@._V1_SX300.jpg',
  'Pokémon - P10 - El desafío de Darkrai': 'https://m.media-amazon.com/images/M/MV5BMTQ4MTYzODUzMF5BMl5BanBnXkFtZTgwMTcxOTk0MDE@._V1_SX300.jpg',
  'Pokémon - P11 - Giratina y el Defensor de los Cielos': 'https://m.media-amazon.com/images/M/MV5BMzFlYWUxN2QtMjZlNC00ZDBlLTljYzEtMTJkYzEyODM3Nzc3XkEyXkFqcGc@._V1_SX300.jpg',
  'Pokémon - P12 - Arceus y la Joya de la Vida': 'https://m.media-amazon.com/images/M/MV5BNzI5Y2NlZGYtOTM5NS00NmI1LWI3YWUtZWY5OTdhMTI5MTVlXkEyXkFqcGc@._V1_SX300.jpg',
  'Pokémon - P13 - Zoroark, el Maestro de las Ilusiones': 'https://m.media-amazon.com/images/M/MV5BOGM4ZGZiMWEtMzIxOS00M2I4LWJkNGQtMzY1YTQzOWM4N2U3XkEyXkFqcGc@._V1_SX300.jpg',
  'Pokémon - P14 - Blanco, Victini y Zekrom': 'https://m.media-amazon.com/images/M/MV5BZjkzNDVjZWYtYTljNS00YmQxLWFkY2UtN2E0NGJlNzE0NDM2XkEyXkFqcGc@._V1_SX300.jpg',
  'Pokémon - P14 - Negro, Victini y Reshiram': 'https://m.media-amazon.com/images/M/MV5BNmMwMzljYTgtY2NmNS00M2FhLWI0YzMtY2Y3MzlmMzBhYTE1XkEyXkFqcGc@._V1_SX300.jpg',
  'Pokémon - P15 - kyurem vs el Espadachín Místico': 'https://m.media-amazon.com/images/M/MV5BNDY4NjA4MjYxNV5BMl5BanBnXkFtZTgwMjM0MDgxMDI@._V1_SX300.jpg',
  'Pokémon - P16 - Genesect y el despertar de una leyenda': 'https://m.media-amazon.com/images/M/MV5BOGQ4MmY0ZWEtNmI4NC00NWZlLWE5ZjEtNWUxNjg2MTY0ZGI3XkEyXkFqcGc@._V1_SX300.jpg',
  'Pokémon - P17 - Diancie y la crisálida de la destrucción': 'https://m.media-amazon.com/images/M/MV5BZmIxNTYzODctY2ZlNS00Njc1LWFkMGUtNTI1MTlhZTFjMjNjXkEyXkFqcGc@._V1_SX300.jpg',
  'Pokémon - P18 - Hoopa y un duelo histórico': 'https://m.media-amazon.com/images/M/MV5BOTc4MzA2OTg1OF5BMl5BanBnXkFtZTgwNzcyNDAwODE@._V1_SX300.jpg',
  'Pokémon - P19 - Volcanion y la maravilla mecánica': 'https://m.media-amazon.com/images/M/MV5BMTk0NzI2Y2YtOGVjYi00YTUwLWEwNmEtODk1YjlhYzQ0ZTY5XkEyXkFqcGc@._V1_SX300.jpg',
  'Pokémon - P20 - ¡Te elijo a ti!': 'https://m.media-amazon.com/images/M/MV5BYTI5M2RmMWUtOGFlMC00M2YxLThiZjUtMjZkNjI3NWQ5NjkwXkEyXkFqcGc@._V1_SX300.jpg',
  'Pokémon - P21 - El Poder De todos': 'https://m.media-amazon.com/images/M/MV5BNWZiMGUzNTMtNmFkMS00YWQwLTgwOTYtNTA4YWFhNjBkM2Q2XkEyXkFqcGc@._V1_SX300.jpg',
  'Pokémon - P22 - Las cronicas de Arceus': 'https://image.tmdb.org/t/p/w500/aGH8biv7gRGeLyxg5Sn4WPcskxV.jpg',
  'Pokémon - P23 - Los secretos de la selva': 'https://m.media-amazon.com/images/M/MV5BY2NlMTFlNjMtNTg2Yi00MzkwLTk2NDUtMWNjZjU2MmEwOTkzXkEyXkFqcGc@._V1_SX300.jpg',
  '1 Dragon Ball Z La batalla de los dioses castellano': 'https://m.media-amazon.com/images/M/MV5BNTkwZTkzZDEtMmFjYy00Y2FmLTkxOTgtZWExMjAwMjZlYmM4XkEyXkFqcGc@._V1_SX300.jpg',
  '2 Dragon ball Z La resurrecion de F castellano': 'https://m.media-amazon.com/images/M/MV5BYjViOWI4ZmMtYzI3Zi00ZDBhLWFiMTUtMTQyMzNlN2RjZWM1XkEyXkFqcGc@._V1_QL75_UY562_CR8,0,380,562_.jpg',
  '3 Dragon Ball Super Broly': 'https://m.media-amazon.com/images/M/MV5BMTA5MTc1M2EtZWQ2Ni00ZmU2LTg3MzQtOTliMjE4OGM0ZWFiXkEyXkFqcGc@._V1_SX300.jpg',
  '4 Dragon Ball Super- Super Hero': 'https://m.media-amazon.com/images/M/MV5BNzA2NmEwZGQtNWI1Ni00MTEyLTlkZDUtZDc5ZTJiOGYyNDQ5XkEyXkFqcGc@._V1_SX300.jpg',
  'Dragon Ball Z OVA Especial El Plan para Exterminar a los saiyajins': 'https://image.tmdb.org/t/p/w500/fAwrVa1RA4RGnGvbx34KhlWdKIw.jpg',
  'Dragon Ball Z OVA Especial Episodio de Bardock': 'https://m.media-amazon.com/images/M/MV5BYmVlODQ4NGEtNzdhMi00NzJjLWIxNTctOThjNTMyMjU1ZWNkXkEyXkFqcGdeQXVyMjUyMTE3MTc@._V1_SX300.jpg',
  'Dragon Ball Z OVA 01 Devuelvanme a mi Gohan 1080p': 'https://m.media-amazon.com/images/M/MV5BNDliM2QwMmQtNGYwZi00ZjkyLWFjMDYtOTdhZjA2Y2M0ZWJkXkEyXkFqcGc@._V1_SX300.jpg',
  'Dragon Ball Z OVA 02 - El Hombre Más Fuerte De Este Mundo': 'https://image.tmdb.org/t/p/w500/3ipNfb1BIs6xGORZETfL2rYUy4w.jpg',
  'Dragon Ball Z OVA 03 - La batalla más grande del mundo': 'https://m.media-amazon.com/images/M/MV5BMTJiMGJlNDQtZDkwZS00MDNiLWIyMDUtYWYyMzI1MmQ0ODFhXkEyXkFqcGc@._V1_SX300.jpg',
  'Dragon Ball Z OVA 04 - Goku es un Super Saiyajin': 'https://m.media-amazon.com/images/M/MV5BNjE0OTMzZmQtZmYxMi00YzcxLTkzZmYtOTEwMDlkZjI2YTE3XkEyXkFqcGc@._V1_SX300.jpg',
  'Dragon Ball Z OVA 05 - Los rivales mas poderosos': 'https://image.tmdb.org/t/p/w500/1hXkEacbCRYYau4dLv4UZPWxKr5.jpg',
  'Dragon Ball Z OVA 06 - Los Guerreros Mas Poderosos': 'https://m.media-amazon.com/images/M/MV5BMTA3OGNiYzItNGNlYy00NGRiLWEwODUtMTJjZTMxNzVjYTY1XkEyXkFqcGc@._V1_SX300.jpg',
  'Dragon Ball Z OVA 07 - La pelea de los Tres Saiyajins': 'https://m.media-amazon.com/images/M/MV5BMmIyYWMwMzgtNzY4NC00MjM5LTkxNWMtMDg1NWE3ODMxODNlXkEyXkFqcGc@._V1_SX300.jpg',
  'Dragon Ball Z OVA 08 - El Poder Invencible': 'https://m.media-amazon.com/images/M/MV5BN2U0MzdjOTItNDg5NS00NWQ0LWE5ZWEtZmRjNDVmY2NmZDFjXkEyXkFqcGc@._V1_SX300.jpg',
  'Dragon Ball Z OVA 09 - La Galaxia Corre Peligro': 'https://m.media-amazon.com/images/M/MV5BMTY5OTM1OGMtYzEyMC00YzkxLWFiMjAtM2IxODM5YWNhNjg3XkEyXkFqcGc@._V1_SX300.jpg',
  'Dragon Ball Z OVA 10 - El Regreso del Guerrero Legendario (2)': 'https://m.media-amazon.com/images/M/MV5BYTg5Y2EyYTItOTc2OS00NWRjLWJjNzEtZjdlNzJiZDI1MmNhXkEyXkFqcGc@._V1_SX300.jpg',
  'Dragon Ball Z OVA 11 - El Combate Final': 'https://m.media-amazon.com/images/M/MV5BM2MyZjViODMtMmNiZi00Y2U5LWEyNDktOTAyYzRhNjFhNTc3XkEyXkFqcGc@._V1_SX300.jpg',
  'Dragon Ball Z OVA 12 - La Fusion De Goku y Vegeta 1080pconverted': 'https://m.media-amazon.com/images/M/MV5BNjIyNGY0OWYtY2JlNS00ODVjLWJiODEtYWNlNWZjNDMzZjUzXkEyXkFqcGc@._V1_SX300.jpg',
  'Dragon Ball Z OVA 13 - El Ataque Del Dragon': 'https://m.media-amazon.com/images/M/MV5BNjU2Mzg1NGItMzZkZS00ODYzLWEwMWItNGNiZTczM2U3M2MxXkEyXkFqcGc@._V1_SX300.jpg',
  'Dragon Ball Z OVA 2008 ¡Hey! Goku y sus': 'https://m.media-amazon.com/images/M/MV5BMmIwN2IzNDctZjEyMi00ZjU1LTk1NjYtZmRiMGFmOTVjZmFjXkEyXkFqcGdeQXVyOTU1NjkyODE@._V1_SX300.jpg',
  'Dragon Ball Z OVA Especial 1 - Bardock El padre de Goku': 'https://m.media-amazon.com/images/M/MV5BMTQwMmMwMDktMmE4Ni00YjVlLWJmNmUtZjIyMTgzMTkwZjIyXkEyXkFqcGc@._V1_SX300.jpg',
  'Dragon Ball Z OVA Especial 2 - Un futuro diferente Gohan y Trunks': 'https://m.media-amazon.com/images/M/MV5BODYxNzdlODYtYjJjMi00ZDI3LTkxYTgtNTRmNmY1ODM5ZDliXkEyXkFqcGc@._V1_SX300.jpg',
  'Dragon Ball - OVA 01 - La Leyenda de Shen Long': 'https://m.media-amazon.com/images/M/MV5BNTA5ZTBiZDEtZDk5Yi00NDA4LTk4MTItMGMwMGQ4NTBhNTc3XkEyXkFqcGc@._V1_SX300.jpg',
  'Dragon Ball - OVA 02 La Princesa Durmiente': 'https://m.media-amazon.com/images/M/MV5BZjI4ZDkwZjQtNDA5NS00OTY4LWIwNDAtMGQ0MzZjOTRkMmY5XkEyXkFqcGc@._V1_SX300.jpg',
  'Dragon Ball - OVA 03 - Una Aventura Mistica': 'https://m.media-amazon.com/images/M/MV5BMmI4YTg1MDYtZWQyYy00NjZjLWJiNTMtZjBhYmMxMzI2ZTVhXkEyXkFqcGc@._V1_SX300.jpg',
  "Fritz el gato (Fritz the cat). - Ralph Bakshi 1.972 USA Animación Comedia 75' Dual+VOSE 283 #": 'https://image.tmdb.org/t/p/w500/aZgHOb5QHvLLn4kxxBTVb0BNqW.jpg',
  'Heavy Metal': 'https://m.media-amazon.com/images/M/MV5BMjRkYWE1ZDUtYjg4Ny00YjAwLWJlZDQtZGU4MWE3ZmNmNjdmXkEyXkFqcGc@._V1_SX300.jpg',
  'TEKKEN - LA PELÍCULA': 'https://image.tmdb.org/t/p/w500/4nGHAliduj9KOFFyyeHFxbsCyUV.jpg',
  'Titan A.E.': 'https://m.media-amazon.com/images/M/MV5BMzYwZTRhMzMtMmRkNi00ODc2LWE0ODktNTUwYzVjMWJhMjViXkEyXkFqcGc@._V1_SX300.jpg',
  '1985 - Astérix Y la sorpresa del César': 'https://image.tmdb.org/t/p/w500/nVxcOIGRxeDy2MpgwPSXRQhTN45.jpg',
  '2014 - Asterix La residencia de los dioses': 'https://image.tmdb.org/t/p/w500/tuBDjGCBeDq4ypT58yfDMGaPOIb.jpg',
  '2023 - Astérix y Obélix y El ReinoMedio': 'https://image.tmdb.org/t/p/w500/gQy5hTqiioNHe85RuPcMyaio9Sp.jpg',
  'Aladdin (1992)': 'https://m.media-amazon.com/images/M/MV5BMmQwYWZjZGItYzc0OC00ZDllLTg3NjItOWIyOWYwMDljMjAyXkEyXkFqcGc@._V1_SX300.jpg',
  'Aladdin y el rey de los ladrones (1996)': 'https://m.media-amazon.com/images/M/MV5BODFkMjE5YzAtMDFkOC00ZDNhLTkwNmQtODk1Y2VhNThlNWJhXkEyXkFqcGdeQXVyNzY1NDgwNjQ@._V1_SX300.jpg',
  'Aladdin, El retorno de Jafar (1994)': 'https://image.tmdb.org/t/p/w500/dpnjhDsWimMUOMsuz2AVsqeU9vL.jpg',
  'Atlantis - El imperio perdido (2001)': 'https://image.tmdb.org/t/p/w500/uR7AKWMDTwyAub5r4QoPPiJImvx.jpg',
  'Basil, el ratón superdetective (1986) - - - LasCositas': 'https://m.media-amazon.com/images/M/MV5BMGZmNDU5OTMtYmRkNC00NDgxLTllNDAtNzFmZDEzNWIzNTViXkEyXkFqcGc@._V1_SX300.jpg',
  'Dumbo (1941)': 'https://m.media-amazon.com/images/M/MV5BNzIzZWZmM2ItNGMzOC00MGFiLTgxODgtNTQ2Mzk3ZWE1MzYxXkEyXkFqcGc@._V1_SX300.jpg',
  'El emperador y sus locuras (2000)': 'https://image.tmdb.org/t/p/w500/X9jChoAotaGU81lEraUVi8RHOe.jpg',
  'Flubber y el profesor chiflado (1997)': 'https://image.tmdb.org/t/p/w500/pvpoHSUkjERCTk0V8BYa9MLknsA.jpg',
  'La espada mágica': 'https://m.media-amazon.com/images/M/MV5BYjEzNjJkNzktYmNmMy00ZmUzLWE3OTMtZTM2ZDU3ODNjOGMyXkEyXkFqcGc@._V1_SX300.jpg',
  'La leyenda de Sleepy Hollow y el Señor Sapo': 'https://m.media-amazon.com/images/M/MV5BZDRkODhiMTMtZDg0ZC00ZTFhLTk2MDAtMWI3ZjcxMmY1OTllXkEyXkFqcGc@._V1_SX300.jpg',
  'Los Aristogatos (1970)': 'https://image.tmdb.org/t/p/w500/s9DsxlbVE1HvHnCz50GdHDBeZRy.jpg',
  'Los Rescatadores (1977 BDRip m1080p x264 Spanish-English AC3 5.1 Subs)': 'https://m.media-amazon.com/images/M/MV5BYjAxMmU2N2UtNjk1MC00YjlmLWI2YzAtYjBlMGM5NWJjOWYzXkEyXkFqcGc@._V1_SX300.jpg',
  'Los.Rescatadores.en.Cangurolandia.(1990).(Spanish.English.Subs).WEBRip.1080p.x264-AC3.DTS': 'https://m.media-amazon.com/images/M/MV5BZjIyYWVhYWUtZTdjYy00NTUxLWExY2YtYjljNWExYjYyMDUxXkEyXkFqcGc@._V1_SX300.jpg',
  'MERLIN EL ENCANTADOR ( rpegc)': 'https://m.media-amazon.com/images/M/MV5BN2U1ZDI3OGMtOTU0Ni00MTAxLTgwYWEtN2QwZDI4ZTQ5MTQ0XkEyXkFqcGc@._V1_SX300.jpg',
  'Oliver y su pandilla (1988)': 'https://image.tmdb.org/t/p/w500/31pu0jSoa6iUouojFnjjlqgOnHB.jpg',
  'Tod y Toby': 'https://m.media-amazon.com/images/M/MV5BY2IxMDIxZTAtMjEyMS00MzY3LTkyM2EtNTVlNTZmMjI1OTRlXkEyXkFqcGc@._V1_SX300.jpg',
  'Toy Story 1': 'https://image.tmdb.org/t/p/w500/jvn7wy3RSNEXnFSXLpH2of2LcV6.jpg',
  'Toy story 2': 'https://m.media-amazon.com/images/M/MV5BNzVmODlhMDEtY2YxZi00OTVjLTlkNTktN2Q2OTRlM2I4M2FhXkEyXkFqcGc@._V1_SX300.jpg',
  'Toy Story 3': 'https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg',
  'Toy Story 4': 'https://m.media-amazon.com/images/M/MV5BMTYzMDM4NzkxOV5BMl5BanBnXkFtZTgwNzM1Mzg2NzM@._V1_SX300.jpg',
  'Toy Story 5 (2026)': 'https://m.media-amazon.com/images/M/MV5BZTI1YTBiNmEtYWUxZi00YzFkLWIzNjMtMmZjMmY2NzM0ZWMzXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
  'Toy Story Buzz Lightyear la pelicula': 'https://m.media-amazon.com/images/M/MV5BZGI3ZjUyM2ItNmFjYy00NGE3LTg2OTYtMTI2MDk0MjIxNDA1XkEyXkFqcGc@._V1_SX300.jpg',
  'Toy Story El tiempo perdido': 'https://m.media-amazon.com/images/M/MV5BOTc2OTA1MDM4M15BMl5BanBnXkFtZTgwNjczMDk5MjE@._V1_SX300.jpg',
  'Toy Story Terror': 'https://m.media-amazon.com/images/M/MV5BNDU5MWI4ZTctYTdlNi00MmQ1LTkzZGUtZmYxYWMyNmQ4MjdiXkEyXkFqcGc@._V1_SX300.jpg',
  'Toy Story Vacaciones en Hawaii': 'https://m.media-amazon.com/images/M/MV5BMTk1NzY0MTY3M15BMl5BanBnXkFtZTgwMjkzMDgwMjE@._V1_SX300.jpg',
  'Tron (1982)': 'https://m.media-amazon.com/images/M/MV5BMTA4Y2VjOWEtMWQ5MS00YWU5LTkxZTMtNzVmMDYyNWFiODU5XkEyXkFqcGc@._V1_SX300.jpg',
  'El Zapatero Y El Ladrón (Versión Del Director) - Subtitulada Al Español por VanSiriusX': 'https://image.tmdb.org/t/p/w500/3OKtFuTxahr7hokPB9aO38qgOfc.jpg',
  'Aqua Teen Hunger Force Colon': 'https://m.media-amazon.com/images/M/MV5BMTc0OTQwNzYyNF5BMl5BanBnXkFtZTcwMDc5NTM0MQ@@._V1_SX300.jpg',
  'Aquí llega Condemor, el pecador de la pradera': 'https://m.media-amazon.com/images/M/MV5BZTc1MTVjMjktMmQ3MC00ZWUzLTkzNDQtNGM0MDc5ZDFkY2ExXkEyXkFqcGc@._V1_SX300.jpg',
  'Brácula, Condemor II (Álvaro Sáenz de Heredia, Chiquito de la Calzada, Bigote Arrocet, 1997)': 'https://image.tmdb.org/t/p/w500/r0WElhXQsuERcxecPimMzgzgcTC.jpg',
  'El mono borracho en el ojo del tigre': 'https://m.media-amazon.com/images/M/MV5BMGVjNzA2Y2QtNzNlOC00ODE2LWE3NDEtMzE4NzUwNjdhZWQzXkEyXkFqcGc@._V1_SX300.jpg',
  'Karate A Muerte En Torremolinos Pedro Temboury 2001 (Reescalada 1280x720.by.VsX)': 'https://image.tmdb.org/t/p/w500/o8tUXtsXdlEy2PguPWrVh88sTTN.jpg',
  'La matanza canibal de los garrulos lisérgicos (1993)': 'https://image.tmdb.org/t/p/w500/mFdRxyQ0BimmDvcvhgsAIrjHt46.jpg',
  'Medio Flipado (Half Baked)': 'https://m.media-amazon.com/images/M/MV5BNTYyMDI1MzMtMzk3MC00MDA5LTgwZTgtZjYxZjc0ZmUwNGMxXkEyXkFqcGc@._V1_SX300.jpg',
  'La novena puerta': 'https://m.media-amazon.com/images/M/MV5BOTQ2ODM2NjktMzJjMC00MWJiLWI2MjMtMzhiOTFmMzc1ZDUyXkEyXkFqcGc@._V1_SX300.jpg',
  'La Soledad del Corredor de Fondo': 'https://m.media-amazon.com/images/M/MV5BZDM3MDA5NGMtZDQ1Yi00ZjdhLTgxNzgtY2UyN2RmNzg2YmZjXkEyXkFqcGc@._V1_SX300.jpg',
  'Memento.(Spanish.English).HDrip.XviD-AC3.by.FitoCorleone.(proteinicos.es)': 'https://image.tmdb.org/t/p/w500/fKTPH2WvH8nHTXeBYBVhawtRqtR.jpg',
  'Miedo Y Asco En Las Vegas': 'https://m.media-amazon.com/images/M/MV5BNjFkNjdiZjUtNzUzNy00NWM5LWFlNDUtNTRiYmJiZWNiYjkwXkEyXkFqcGc@._V1_SX300.jpg',
  'Naufrago en la luna (2009)': 'https://image.tmdb.org/t/p/w500/jRrdzFcJUTz9yb6A5quSQrvhJDB.jpg',
  'Tenemos que hablar de Kevin': 'https://m.media-amazon.com/images/M/MV5BMjE0NDE0MjYxNF5BMl5BanBnXkFtZTcwNjM2NTY5Ng@@._V1_SX300.jpg',
  'Una mirada a a la oscuridad (2006)': 'https://m.media-amazon.com/images/M/MV5BMThiNWRmNDQtOWM0ZC00YjI1LWFmMmMtYzBhZjMzODk4NmJmXkEyXkFqcGc@._V1_SX300.jpg',
  'Duelo silencioso..(Akira Kurosawa,1949).(Spanish.Japanese).DVD-Rip.XviD-AC3.by.Marc27.(filibusteros.com)': 'https://image.tmdb.org/t/p/w500/7XhjAEimUgiGjVzn5d3CvH5BFg1.jpg',
  'El Angel Borracho (Akira Kurosawa, 1948) (Spanish Japanese) Hdrip Xvid-Ac3 By Araubi (Proteinicos Es)': 'https://image.tmdb.org/t/p/w500/aAOyl6mo18xMSB5RcvR1BnFENRW.jpg',
  "El infierno del odio (Tengoku to jigoku). - Akira Kurosawa 1.963 Japón Negro 144' 369 #": 'https://image.tmdb.org/t/p/w500/9c87PSaPcoZzAGbJKQLAcYiqGRy.jpg',
  'La.fortaleza.escondida.(Akira.Kurosawa,.1958).(Spanish.Japanese).HDrip.XviD-AC3.by.araubi.(proteinicos.es)': 'https://image.tmdb.org/t/p/w500/qqW9ILhtVN29Bkr4ZNTjw29Q6nL.jpg',
  'Los canallas duermen en paz (1960)': 'https://image.tmdb.org/t/p/w500/8zIUesEI8a5ScJ4adThcYhm73k3.jpg',
  'los siete samurais - shichinin no samurai - seven samurai -(1954) - spanish': 'https://image.tmdb.org/t/p/w500/zr4DkzWIMjaWtj6hlsbN6dnNeTX.jpg',
  'Los sueños de Akira Kurosawa..(Akira Kurosawa.1990).(Spanish.Japanese).DVD-Rip.XviD-mp3.by.GCC.(centralclasico.com)': 'https://image.tmdb.org/t/p/w500/tn9OJznv1Ii6uXA4p6eZT5tnEo2.jpg',
  'Trono de sangre (1957)': 'https://image.tmdb.org/t/p/w500/4qggbvXbBZjvEALqEjyAQdaMTfM.jpg',
  'Yojimbo (El mercenario)(1961, Akira Kurosawa)Akantor': 'https://m.media-amazon.com/images/M/MV5BYzFkODA1N2QtY2UyMC00NTMwLWEyNzctMmE3YjIzNzE1MzY4XkEyXkFqcGc@._V1_SX300.jpg',
  'Dune (Version Extendida)(Spanish English Subs) HD1080p x264-AC3': 'https://m.media-amazon.com/images/M/MV5BMGJlMGM3NDAtOWNhMy00MWExLWI2MzEtMDQ0ZDIzZDY5ZmQ2XkEyXkFqcGc@._V1_SX300.jpg',
  'Corazón salvaje..(David Lynch.1990) DVDRip Xvid AC3-Mp3 English-Spanish': 'https://m.media-amazon.com/images/M/MV5BMjIyZTI1MzQtMmMxMS00MTkwLWFlNGMtMzQ2OThlZWNiM2YwXkEyXkFqcGc@._V1_SX300.jpg',
  'David Lynch - Inland Empire (2006)': 'https://image.tmdb.org/t/p/w500/7mP7TUoS5MQjPfjmfYMYYvlsbUy.jpg',
  'Eraserhead.(Cabeza borradora).1977.David Lynch.by Juggernaut.VOSE': 'https://image.tmdb.org/t/p/w500/j8Z0M4rUmxVFtvpN7bZ2JTASrsy.jpg',
  'Lost Highway (1997. David Lynch)(Carretera perdida).(Spanish.English.Subs).BDrip.1080p.HDR.HEVC.10b-AC3.by.nara': 'https://image.tmdb.org/t/p/w500/vFIhGJuUfCSGTFj5fgLCbBAtxt2.jpg',
  'Mulholland.Drive.(2001).(Spanish.English.spanishSub.englishsub).HD.1080p.x264-AC3.by.Rowdy.(emulesonic.com)': 'https://m.media-amazon.com/images/M/MV5BNjliY2UwMjQtYjVlNi00NzExLTg1MDMtMjE2OTYwYjI0NTcxXkEyXkFqcGc@._V1_SX300.jpg',
  'Terciopelo azul (Blue velvet) (David Lynch,1986)': 'https://image.tmdb.org/t/p/w500/rzcigN8ujeVJiEKGP3y3mJybvii.jpg',
  'The Elephant Man (David Lynch, 1980) 1080p': 'https://m.media-amazon.com/images/M/MV5BMGE3MDZhNmMtMmUxZS00MDJmLTgxYmQtOGU4ODU0Y2JmNDI1XkEyXkFqcGc@._V1_SX300.jpg',
  '1966 - 1996 - The Short Films Of David Lynch (David Lynch, 1966~1996) x264 (576P) Ac3 (Eng) Sub (Ita) By Sparco (1)': 'https://image.tmdb.org/t/p/w500/86WCJiXMvPaXEnN02sFjiAbhdB.jpg',
  'Corto The amputee.(1974.David.Lynch).(English.Spanishsub).DVD-Rip.XviD-mp3.by.jose1969.(exploradoresp2p.com)': 'https://image.tmdb.org/t/p/w500/6yRz5TOhNCbpOQ76daKSPh8x3Fe.jpg',
  'Abierto Hasta El Amanecer (1996) Robert Rodriguez - George Clooney, Harvey Keitel, Juliette Lewis, Quentin Tarantino - Spanish - Thriller AcciÃ³n Terror FantÃ¡stico Comedia Negra': 'https://image.tmdb.org/t/p/w500/4hPWRrWGFD6WuuzihqDbYMS51pc.jpg',
  'Four Rooms (1995)': 'https://m.media-amazon.com/images/M/MV5BMmNlMjE5YTEtZTU1My00MDc1LTgwNzctNTZlYmJmNTM3ZjYzXkEyXkFqcGc@._V1_SX300.jpg',
  'Pulp Fiction (1994)': 'https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_QL75_UY562_CR3,0,380,562_.jpg',
  'Reservoir Dogs.(Reservoir Dogs).(Quentin Tarantino, 1992).H5534H.F137887F.(Spanish.English.Subs).Micro4K.2160p.x265.HDR10.Dolby.Vision.10Bits-AC3.by.lagartish': 'https://m.media-amazon.com/images/M/MV5BMmMzYjg4NDctYWY0Mi00OGViLWIzMTMtYWNlZGY5ZDJmYjk3XkEyXkFqcGc@._V1_SX300.jpg',
  'Serguei Eisenstein 1923 El Diario de Glumov': 'https://m.media-amazon.com/images/M/MV5BZmU3MTEzNjEtYTRiZi00ZmY4LTkwNzYtNDFmYTk1NWY3ZjAyXkEyXkFqcGdeQXVyMjYxMzY2NDk@._V1_SX300.jpg',
  'Serguei Eisenstein 1937 El Prado de Bezhin (Bezhin Meadow) (inacabada)': 'https://image.tmdb.org/t/p/w500/tkzxPNzPlfgV38FJqNrudRg6xa1.jpg',
  'Asalto al banco central (1983)': 'https://image.tmdb.org/t/p/w500/84UTUCUF7KFvkoTIjS7teiHWmRK.jpg',
  'El Pico 2': 'https://image.tmdb.org/t/p/w500/fc4lQVxiWIuPAw1d6jpg5UaMOiO.jpg',
  'Los violadores del amanecer (1978)': 'https://image.tmdb.org/t/p/w500/13PaVZDDSd717Q0aFh7P4I9Smin.jpg',
  'Perros callejeros 2 (1979)': 'https://m.media-amazon.com/images/M/MV5BMzFlY2MzYWItMzExZC00N2U3LTk5M2EtZmVjNDdhYmM4NWRmXkEyXkFqcGc@._V1_SX300.jpg',
  '2001 Odisea en el Espacio - Stanley Kubrick (1968) 7,7': 'https://image.tmdb.org/t/p/w500/pGabanxaE2YvN4jhZuSN3oXO0mi.jpg',
  'El Resplandor (Version Extendida) (1980) new': 'https://image.tmdb.org/t/p/w500/mm003Mj2e9kJRsrxiVdPn2BSBPh.jpg',
  'La Chaqueta Metálica (1987) - new': 'https://image.tmdb.org/t/p/w500/6CX7BcyD8Xd5AQ7myNs0UE4mu6c.jpg',
  'La.naranja.mecanica.(1971.Stanley.Kubrick).(Spanish.English.Subs).BDrip.1080p.x264.AC3.by.Nostrom0 new': 'https://image.tmdb.org/t/p/w500/p40pYh2EBPoyVyqw6qy2PAZkFVA.jpg',
  'Christine (1983) (Español)': 'https://images.justwatch.com/poster/9621681/s718/christine.jpg',
  'Cujo de Stephen King (1983) (25 Anniversary Edition) (Spanish English Subs) Bdrip 720p X264-AC3': 'https://image.tmdb.org/t/p/w500/x8PUdXCGSM6iDzzMonLRJukgGci.jpg',
  'El cementerio viviente 2 (Pet Sematary Two) (1993)': 'https://image.tmdb.org/t/p/w500/A1qXTzGHIyCQmJbmEZL47KIqRhL.jpg',
  'El.cementerio.viviente.(Pet.sematary.1989).(Spanish.English.Subs).BDrip.720p.x264-AC3.by.rodosky.(proteinicos.es)': 'https://image.tmdb.org/t/p/w500/rjL6WhvdnaEqwMfM3Crscjs0nNP.jpg',
  'It (Eso) (1990)': 'https://image.tmdb.org/t/p/w500/uuTYA9LIlIRCFMgFlxWb1KznfEx.jpg',
  'La Rebelion De Las Maquinas - Maximum Overdrive - 8 Days Of Terror - 1986 (Stephen King) (Spa-Eng) Emilio Estévez': 'https://image.tmdb.org/t/p/w500/8lROOm3zgANbYZwEKaTqVfHIJsE.jpg',
  'Maleficio (Thinner Stephen King 1996).720p.BluRay.x264.(Spanish.English)': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/maleficio.png',
  'Proverbio Chino (2006)': 'https://image.tmdb.org/t/p/w500/sAg6tJtLT5zq6oveDqlQ6zRy0YJ.jpg',
  'The Magic Pear Tree (1968) Directed by Charles Swenson- Oscar Nominated Short': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/the_magic_pear_tree.jpg',
  'Trapito (Manuel García Ferré, 1975)': 'https://image.tmdb.org/t/p/w500/pFKLGKMIPQVPi6entlTnubx9OPD.jpg',
  'Operación Ogro (Gillo Pontecorvo,1979)': 'https://m.media-amazon.com/images/M/MV5BMjRiMWYyMjYtMjA5MS00Y2U0LTk0NmItMDQ0MjRhZTNmOTE2XkEyXkFqcGc@._V1_SX300.jpg',
  'Padre coraje (2002) (Benito Zambrano).dvdrip.x264.ac3.castleaco': 'https://m.media-amazon.com/images/M/MV5BY2RhMjIzN2EtY2IzZC00MzU0LTk5NjYtZDZiODAxYmNmMjY1XkEyXkFqcGc@._V1_SX300.jpg',
  'El caso Almeria (1984)': 'https://image.tmdb.org/t/p/w500/lVs02YmwvbHO9HuK5myv7Smf2gN.jpg',
  'El Pico (1983)': 'https://image.tmdb.org/t/p/w500/mlDv6yZ2Qoyq92xvmC56SQ2X2D1.jpg',
  'La estanquera de Vallecas (1987)': 'https://image.tmdb.org/t/p/w500/iTNv9ZlNFVsPevNS7yEyHvna5nf.jpg',
  'Perras Callejeras (1985)': 'https://image.tmdb.org/t/p/w500/aM8fZRllfZabWqvJD4Ig3n2PjrP.jpg',
  'Yo el Vaquilla (1985)': 'https://image.tmdb.org/t/p/w500/giOeARCc0nw27IJSFpTs0RrBJo4.jpg',
  'El Infierno (La Divina comedia de Dante) (Con rótulos originales) (1911)': 'https://image.tmdb.org/t/p/w500/2XlfmegPej7MqVXd82WbO2Zvf5L.jpg',
  'El Infierno (La Divina comedia de Dante) (Rótulos en español) (1911)': 'https://image.tmdb.org/t/p/w500/2XlfmegPej7MqVXd82WbO2Zvf5L.jpg',
  'El laberinto del Fauno - 2006 -': 'https://image.tmdb.org/t/p/w500/gWPkUFGlO7ZIiArUcWRBmvAwVjB.jpg',
  'Serguei Eisenstein 1924 La Huelga': 'https://image.tmdb.org/t/p/w500/qsULy0fRUwqvrX4JJhGrqKXpeNa.jpg',
  'Serguei Eisenstein 1927 Octubre': 'https://image.tmdb.org/t/p/w500/4HTqU5e3gQbiZwyXIa1ywb6aNlH.jpg',
  '7 Vírgenes (2005)': 'https://image.tmdb.org/t/p/w500/g3o2jxOM3IpYuT7RPACFNeChYHR.jpg',
  'Colegas (1982)': 'https://image.tmdb.org/t/p/w500/hAlIzdwCGKCFwr3BOE6S86NzsWi.jpg',
  'Días contados (1994)': 'https://image.tmdb.org/t/p/w500/qf1IQifbxAqZGKItFDgYBHIemRV.jpg',
  'El diputado (1978)': 'https://image.tmdb.org/t/p/w500/1zObGiy4FgTZx1IDam53s1lN44E.jpg',
  'Historias Del Kronen (1995)': 'https://image.tmdb.org/t/p/w500/vulTVwoMoy1IE1IRJhihHYQ6H2H.jpg',
  'La Reina Del Mate (1984)': 'https://image.tmdb.org/t/p/w500/b7IKfFlhIwex57td6b1kAGaQxTs.jpg',
  'Perros Callejeros (1977)': 'https://image.tmdb.org/t/p/w500/fbUlbqOYsFHQMHYsew4b0gtQw9S.jpg',
  'Ratas de la ciudad (1985)': 'https://image.tmdb.org/t/p/w500/6hnCjxxGkfMFRSZL017eRHZX5Hi.jpg',
  'Todos Me Llaman Gato (1981)': 'https://image.tmdb.org/t/p/w500/dZHfMB92FzzLf1vjt1ZhFNhBgMb.jpg',
  'Super Mario Bros La pelicula (2023)': 'https://image.tmdb.org/t/p/w500/4CDkQMpNDTtVKwS0BBZw5RIXDtY.jpg',
  'Resurrección (1999) HD 1080 - Película Completa en Español (Castellano). #peliculas #2025 #1999': 'https://m.media-amazon.com/images/M/MV5BM2I5NWM1NzAtOTU4MC00Mzk2LTliZjItNjA1MDgwMTJjZmQ2XkEyXkFqcGc@._V1_.jpg',
  'Una mirada a a la oscuridad (2006)': 'https://play-lh.googleusercontent.com/WEcGXUB97Jy1c5QvUyyT19vgsydiu0woE-DigscTrici7dIux2W_KJ8oCmtDuhyRa_P7Or8nb-Jo-0RPwP4',
  'Relatos de Disney Vol. I El Principe Y El Mendigo - La Leyenda De Sleepy Hollow': 'https://image.tmdb.org/t/p/w500/hn985uJJtaBIu46lFLVYeYZd1GT.jpg',
  'Relatos de Disney Vol. II El Patito Feo Y Otros cuentos': 'https://image.tmdb.org/t/p/w500/cLUM6AHSK4HnUtT78jlAznWQ3T3.jpg',
  'Relatos de Disney Vol. III Donald En El País De Las Matemáticas - Franklin y yo - 24 Inventos Modernos': 'https://image.tmdb.org/t/p/w500/1VIk3O5qX80FQAvGKueJeg3cYH7.jpg',
  'Relatos de Disney Vol. IV La Liebre Y La Tortuga - Otros Cortos': 'https://image.tmdb.org/t/p/w500/9CQ22jfqaV9rq6gPnAC53oQ0EIn.jpg',
  'Relatos de Disney Vol. V Los Tres Cerditos - Fernandito El Toro - Los Tres Mosqueteros Ciegos': 'https://image.tmdb.org/t/p/w500/mooNeFE8ziSsaY8GhP2i1JSQVrm.jpg',
  'Relatos de Disney Vol. VI El Dragon Chiflado - Mickey Y Las Habichuelas Magicas': 'https://image.tmdb.org/t/p/w500/o3pxSdoO3XZhCBHKvk6AjdsdBkb.jpg',
  'The Thief and the Cobbler Recobbled Cut (Traducido y subtitulado por VanSiriusX)': 'https://image.tmdb.org/t/p/w500/3OKtFuTxahr7hokPB9aO38qgOfc.jpg',
  'Angerla Kirkwook - It\'s time to blah blah': 'https://freight.cargo.site/t/original/i/426b2110e0d3b4a593e0288f3b1882626deb424d18ef2e93dcc3c28006479240/Illo24_Experiment1_Concept_V2_Web.jpg',
  'Yoji Kuri — AU FOU!': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/au_fou.png',
  'THE ELECTRIC WIZARD - EPISODE FOUR - THE CULT OF DOOM MOUNTAIN (1080p 12fps H264-128kbit AAC)': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/electric_wizard.png',
  'THE ELECTRIC WIZARD - EPISODE THREE - THE COSMIC REALM (1080p 12fps H264-128kbit AAC)': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/electric_wizard.png',
  'THE ELECTRIC WIZARD - EPISODE TWO - THRASHWORLD (1080p 12fps H264-128kbit AAC)': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/electric_wizard.png',
  'THE ELECTRIC WIZARD (1080p 12fps H264-128kbit AAC)': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/electric_wizard.png',
  'THE SOCKS AND SQUIMMY SHOW - EPISODE ONE - THE VISITOR (1080p 12fps H264-128kbit AAC)': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/socks_squimmy.png',
  'Blue Shining (Stanley Kubrick x David Lynch) on Vimeo': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/blue_shining.png',
  'Chicos Perversos (1983)': 'https://preview.redd.it/bad-boys-1983-v0-qrcz1hs8wqje1.jpeg?width=1080&crop=smart&auto=webp&s=c8fbadb915d5c0c97d8ac98c54938ba934284a11',
  'Perros callejeros III': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/perros_callejeros_3.jpg',
  'Perros callejeros Tres días de libertad (1995) Cierre final': 'https://image.tmdb.org/t/p/w500/E9YGCZuRxGBXTTVdVq8bhSetLO.jpg',
  'La Malcriada - Mr. Pizza Serie Completa': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRteKKUo4SMvHTIL8OixHTgrLToN_bnrXfgeUsN-PGWuqGzKN1_jzvS_120GV1VgfE&s=10&ec=121902086',
  'Chocolate (1980)': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/chocolate_1980.jpg',
  'Our War Game (2000) - WEBDL-1080p Proper': 'https://m.media-amazon.com/images/M/MV5BNWNmOTY5Y2YtNGNiNi00M2IxLTlhYjktNDIwMzcyYzE0MDdkXkEyXkFqcGc@._V1_.jpg',
  'Street Fighter II Animated Movie': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/sf2_animated_movie.jpg',
  'Super Mario Bros (La Pelicula) (1993)': 'https://es.web.img3.acsta.net/medias/nmedia/18/86/19/98/20435979.jpg',
  'Phoenix Wright Ace Attorney (2012) (dual cast+jap)': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_YDLiurUy9YbiRUbgnDId6bf5D9zWHkbkqPtfJ0Z22Q&s=10',
  'Esto es un Atraco': 'https://image.tmdb.org/t/p/w500/gvAJfhqbZqAoaN4hzA9htk8QWq3.jpg',
  'La Corte del Faraon': 'https://image.tmdb.org/t/p/w500/7RPzwXMcYR0HzdEcd0VUIxdEwc2.jpg',
  'Ni Te Cases Ni Te Embarques': 'https://image.tmdb.org/t/p/w500/29tc1Mkv1f2gUmBYre6ZJhePJbl.jpg',
  'La Loca Historia de los Tres Mosqueteros': 'https://image.tmdb.org/t/p/w500/fBEeNB5Znt8N2fjjYBgNNvl9xC5.jpg',
  'Aqui Huele a Muerto': 'https://m.media-amazon.com/images/M/MV5BNGY0NmZiODctYTkzNC00YjI4LTliYTQtOTNmZTc0NjQ2ZTQ4XkEyXkFqcGdeQXVyODI2MDA4NQ@@._V1_SX300.jpg',
  'El Robobo de la Jojoya': 'https://m.media-amazon.com/images/M/MV5BMjcxNTE2NGEtOGVlNy00MWJjLTljYmItM2VjOGI0M2NiNzc1XkEyXkFqcGc@._V1_SX300.jpg',
  'Los chicos del maiz': 'https://es.web.img2.acsta.net/medias/nmedia/18/92/53/30/20204975.jpg',
  'Hocus': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/hocus_pocus.jpg',
  'Bio Menace': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/bio_menace.jpg',
  'Duke Nukem II': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/duke_nukem2.jpg',
  'Jazz Jackrabbit': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/jazz.jpg',
  'Monster Bash': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/monster_bash.jpg',
  'Oscar': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/oscar.jpg',
  'Realms of Chaos': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/realms_of_chaos.jpg',
  'Secret Agent': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/secret_agent.png',
  'Trivia Whiz': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/trivia_whiz.webp',
  'Hollywood Trivia': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/hollywood_trivia.jpg',
  'Navajeros': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/navajeros.jpg',
  'Una carta para Momo': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/una_carta_para_momo_v2.jpg',
  'Los niños lobo': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/los_ninos_lobo_v2.jpg',
  'Bubble Bobble': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/bubble_bobble.jpg',
  'Claw': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/claw.jpg',
  'Juego de Tronos': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/juego_de_tronos.jpg',
  'Juego de tronos': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/juego_de_tronos.jpg',
  'La casa del dragón': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/la_casa_del_dragon.jpg',
  'La casa del dragon': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/la_casa_del_dragon.jpg',
  'Keen Dreams': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/commander_keen_dreams.jpg',
  'Commander Keen Dreams': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/commander_keen_dreams.jpg',
  'Commander Keen - Dreams': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/commander_keen_dreams.jpg',
  'Keen 4': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/commander_keen4.jpg',
  'Commander Keen 4': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/commander_keen4.jpg',
  'Los Justicieros': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/los_justicieros.jpg',
  'El Castillo en el cielo - Tenk\u016b no Shiro Laputa': 'https://www.jbhifi.com.au/cdn/shop/products/134794-Product-0-I_ac1f5019-39f5-41c4-9fd7-8590c3ac70db.jpg?v=1572269844',
  'Tenshi no Tamago': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjEVQdlw3Wp6AlmgWykaN6Ip_xgwoMjuKvOnhuZx822A&s=10',
  'Bram Stoker Dracula': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/bram_stoker.jpg',
  'Continuum': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/continuum.jpg',
  'Extreme Pinball': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/extreme_pinball.jpg',
  'Gods': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/god.jpg',
  'Hugo 1 - House of Horrors': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/hugo_1.jpg',
  'Hugo 2 - Whodunit': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/hugo_2.jpg',
  'Hugo 3 - Jungle of Doom': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/hugo_3.jpg',
  'Jill of the Jungle - Trilogy': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/jill.jpg',
  'Monty Pythons Flying Circus': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/monty_python.jpg',
  'Mystic Towers': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/mystic_towers.jpg',
  'Nitemare 3D': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/nitemare.jpg',
  'Pickle Wars': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/pickle_wars.jpg',
  'Prince of Persia 2': 'https://images.igdb.com/igdb/image/upload/t_cover_big_2x/co2ek1.jpg',
  'Shufflepuck Cafe': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/shufflepuck.jpg',
  'Silverball': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/silverball.jpg',
  'Aldos Adventure': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/aldo.jpg',
  'Amys Fun 2-3': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/amy.jpg',
  'Antarctic Adventure': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/antarctic.jpg',
  'Arcy 2': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/arcy_2.jpg',
  'Billy the Kid Returns': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/billy_the_kid.jpg',
  'Captain Comic': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/captain_comic.jpg',
  'Catacomb Abyss': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/catacomb_abyss.jpg',
  'Catacomb Apocalypse': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/catacomb_apocalypse.jpg',
  'Catacomb Armageddon': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/catacomb_armageddon.jpg',
  'Charly the Clown': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/charly.jpg',
  'Cold Dream': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/cold_dream.jpg',
  'Dangerous Dave': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/dave.png',
  'Fire and Ice': 'https://upload.wikimedia.org/wikipedia/en/1/1d/Fire_and_Ice_cover_art_%28Atari_ST%29.jpg?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original',
  'Helious': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/heliou.jpg',
  'Heros - The Sanguine Seven': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/heros.jpg',
  'Hexxagon': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/hexxagon.jpg',
  'Hexxagon 2': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/hexxagon_2.jpg',
  'In Search of Dr Riptide': 'https://static.wikia.nocookie.net/doctorriptide/images/e/e1/Manaccom_catalog_dr_riptide_front.png/revision/latest/scale-to-width-down/284?cb=20220702092753',
  'Krypton Egg': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/kegg.png',
  'Monty Pythons Flying Circus': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/monty_python.jpg',
  'Night Raid': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/night_raid.jpg',
  'Radix': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/radix.jpg',
  'Rodge Rock in Retroactive': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/rodge.jpg',
  'Schof!': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/schof.jpg',
  'ScubaVenture': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/scubaventure.jpg',
  'Sinaria - Lost in Space': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/sinaria.jpg',
  'SkyRoads': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/skyroads.jpg',
  'SkyRoads - Xmas Special': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/skyroads.jpg',
  'Super Cauldron': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/super_cauldron.jpg',
  'Vinyl Goddess from Mars': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/vinyl_goddess.jpg',
  'Word Rescue Plus': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/word_rescue_plus.jpg',
  'Asterix and Obelix': 'https://upload.wikimedia.org/wikipedia/en/c/cc/Asterix_%26_Obelix_PC_cover.jpg?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original',
  'Dangerous Dave - Dave Goes Nutz': 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6gjs.webp',
  'Dangerous Dave 2 - Risky Rescue': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7FYnnvKJFN3Lf5L3IOt73l_J68TnEOBNetiCPJeoY_XjWkmt17kVaQ6L-&s=10',
  'Dangerous Dave 3 - Pirates Hideout': 'https://images.squarespace-cdn.com/content/v1/5fef3318f8ce9b562500206e/1639952811081-Z6RXL9LA34CNUC4KCS2K/library-capsule-600x900.jpg?format=750w',
  'Dangerous Dave 4 - Copyright Infringement': 'https://howlongtobeat.com/games/125805_Dangerous_Dave_in_Copyright_Infringement.jpg',
  'Dangerous Dave 5 - Haunted Mansion': 'https://cdn.mobygames.com/covers/5040862-dangerous-dave-in-the-haunted-mansion-dos-front-cover.jpg',
  'Dork\'s Dreams': 'https://raw.githubusercontent.com/vansiriusxbox360-web/terabox-m3u/main/custom-posters/dorks.png',
  'Duke Nukem - Episodio 1 Shrapnel City': 'https://images.launchbox-app.com/387f80b1-eecc-4d9a-ad39-67274f74fcc5.jpg',
  'Duke Nukem - Episodio 2 Moonbase': 'https://images.launchbox-app.com/387f80b1-eecc-4d9a-ad39-67274f74fcc5.jpg',
  'Duke Nukem - Episodio 3 Future': 'https://images.launchbox-app.com/387f80b1-eecc-4d9a-ad39-67274f74fcc5.jpg',
  'Mutant Space Bats of Doom': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYGjjHaamyQn39FHutmlVQwO9dKuUzDpSs8wN1Vjy0PsNjs9eRWK6QFFM7&s=10',
  'Prince of Persia': 'https://images.igdb.com/igdb/image/upload/t_cover_big_2x/co2ek1.jpg',
  'Avatar la leyenda de Aang El ultimo Airbender (2026)': 'https://image.tmdb.org/t/p/original/AbUa37L0mRs4RtMLvSD6cWZcPJP.jpg',
  'Donkey Kong Country': 'https://m.media-amazon.com/images/M/MV5BOTNlM2MxZDktMzMyZC00Mzg3LThjZTUtNjRmNzcwYzIxM2FmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
};

const CHILD_INHERIT_GROUP_ICON = new Set([
  'Festivales por capis',
  'Dragon Ball Z - Selecta Vision/1. Saga Saiyan (1-35)',
  'Dragon Ball Z - Selecta Vision/2.Saga Freezer (36-107)',
  'Dragon Ball Z - Selecta Vision/3.Saga Garlick Jr. (108-117)',
  'Dragon Ball Z - Selecta Vision/4.Saga Androides y Cell (118-194)',
  'Dragon Ball Z - Selecta Vision/5.Saga del Otro Mundo (195-199)',
  'Dragon Ball Z - Selecta Vision/6.Saga Buu (200-291)',
  'Tres amigos y Jerry',
  // Pokémon: los capítulos de cada región heredan la imagen de su carpeta
  'Pokémon/1. Kanto',
  'Pokémon/2. Johto',
  'Pokémon/3. Hoenn',
  'Pokémon/4. Sinnoh',
  'Pokémon/5. Teselia',
  'Pokémon/6. Kalos',
  'Pokémon/7. Alola',
  'Pokémon/8. Galar (Viajes Pokémon)',
  'Pokémon/9. Paldea (Pokémon Horizontes)',
  'Pokémon/Crónicas Pokémon',
  'Pokémon/La conserje Pokémon',
  'Pokémon/Pokémon Generations',
  'Pokémon/Pokémon Megaevolución',
  'Pokémon/Pokémon Origin',
]);
const FILE_CLEANNAME_ALIASES = {
  '1999 - Astérix y Obélix - Contra el César': 'Asterix and Obelix vs Caesar',
  '2002 - Astérix y Obélix - Misión Cleopatra': 'Asterix and Obelix Mission Cleopatra',
  '2012 - Astérix y Obélix - Al servicio de su majestad': 'Asterix and Obelix God Save Britannia',
  'Howard Un nuevo heroe 1986 Lea Thompson,Jeffrey Jones Ficcion Extraterrestres': 'Howard the Duck',
  'Pinocho, la leyenda (1996) m720p x264 MP3 2.0 EspaÃ±ol': 'The Adventures of Pinocchio',
};

module.exports = {
  TITLE_ALIASES,
  CUSTOM_POSTERS,
  PATH_POSTER_SUFFIXES,
  FILE_TITLE_ALIASES,
  FILE_POSTER_URLS,
  CHILD_INHERIT_GROUP_ICON,
  FILE_CLEANNAME_ALIASES,
};
